### ISSUE TITLE
Unhandled promise rejection in Fedora

### ISSUE THREAD

**Issue by twhiston** [okonek/tidal-cli-client#11]
On Fedora 27, having made sure I have all the dependencies, I try to search for an artist, but when I do the program crashes with the following error

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'tw' of undefined
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

**Comment by okonek** [comment]
Have got W3M and MPV installed?

**Comment by twhiston** [comment]
yes

**Comment by TomFarrow** [comment]
(node:25335) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tw' of undefined────────────────────────────────────────────────────────┐
    at new module.exports (/usr/local/lib/node_modules/tidal-cli-client/app/UI/SquareImage.js:9:41)                                                            │
    at new module.exports (/usr/local/lib/node_modules/tidal-cli-client/app/UI/ArtistPanel.js:25:28)
    at ActivityPanel.showPanel (/usr/local/lib/node_modules/tidal-cli-client/app/UI/ActivityPanel.js:34:37)
    at Object.communicationEvents.subscribe [as handler] (/usr/local/lib/node_modules/tidal-cli-client/app/UI/MainScreen.js:102:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:25335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

I'm seeing this issue on Ubuntu.

$ apt list --installed | grep "mpv\|w3m"
mpv/bionic,now 0.27.0-2ubuntu4 amd64 [installed]
w3m/bionic,now 0.5.3-36build1 amd64 [installed]

**Comment by okonek** [comment]
Have you got the latest version of the app?

**Comment by twhiston** [comment]
In my case yes, installed with `sudo npm -g i tidal-cli-client@latest`

**Comment by RedHatter** [comment]
I am also experiencing this issue.

**Comment by ALGW71** [comment]
(node:2500) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tw' of undefined─────────────────────────────────────────────────────────────┐
    at new module.exports (/usr/local/lib/node_modules/tidal-cli-client/app/UI/SquareImage.js:9:41)                                                            │
    at new module.exports (/usr/local/lib/node_modules/tidal-cli-client/app/UI/ArtistPanel.js:25:28)
    at ActivityPanel.showPanel (/usr/local/lib/node_modules/tidal-cli-client/app/UI/ActivityPanel.js:34:37)
    at Object.communicationEvents.subscribe [as handler] (/usr/local/lib/node_modules/tidal-cli-client/app/UI/MainScreen.js:102:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:2500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Also getting this on Ubuntu.

**Comment by okonek** [comment]
Sorry, I haven't got a lot of time, but I'll try to help you as soon as possible

**Comment by okonek** [comment]
Could you please check if you have w3m-img installed? On some systems it is a different install from w3m. Thank you for your help! :+1:

**Comment by okonek** [comment]
Are you installing with apt? Have you got the universe repository enabled?

**Comment by ALGW71** [comment]
That worked but I still can't play music. I think there is something wrong
with my node js or npm, because 8 installed from Chris lea repository...
Don't how to remove everything now...

**Comment by okonek** [comment]
What error have you got?

**Comment by ALGW71** [comment]
loadDep:uuid → get        ▄
╢██████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current:
{"node":"4.2.6","np/usr/local/bin/tidal-cli ->
/usr/local/lib/node_modules/tidal-cli-client/app/index.js
/usr/local/lib
└─┬ tidal-cli-client@1.4.1
  └── tidalapi@0.2.3  (git+
https://github.com/okonek/TidalAPI.git#5778ddd198aad3bda8665330b70aef4fd5109f68
)


I can get Tidal-cli up and running. But no access to artists or anything.

I type ":" then "artist" hit return, but then the type box dissappears...

I am on ubuntu not fedora

**Comment by ALGW71** [comment]
Sorry I'm new to ubuntu and linux so I have no idea what I'm doing...

**Comment by ALGW71** [comment]
node is now version 9.9.0
nodejs v4.2.6
npmn 5.6.0

**Comment by ALGW71** [comment]
Final question.

Where is the exact list of all the dependencies?

You write this, "Install other dependencies with npm install and run with npm
run app"

But where do I find the list of all those i need to install?

Also when i type npm run app.

I get this error

.npm run app
npm ERR! path /home/alexgw/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open
'/home/alexgw/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alexgw/.npm/_logs/2018-04-04T09_05_32_618Z-debug.log

**Comment by leynebe** [comment]
Can confirm same issue on Fedora 27 with necessary packages installed.
Using `tidal-cli` and then pressing CTRL+P crashes it.

> (node:7775) UnhandledPromiseRejectionWarning: undefined
> (node:7775) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:7775) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by okonek** [comment]
Could you update to the latest version and see if it helped?
