### ISSUE TITLE
exec problem

### ISSUE THREAD

**Issue by DevStorage** [okonek/tidal-cli-client#18]
/usr/local/lib/node_modules/tidal-cli-client/app/Track.js:8
    async updateStreamURL(tidalApi) {
          ^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tidal-cli-client/app/TidalApi.js:2:15)
Xubuntu 17.10
mpv and w3m installed.

**Comment by DevStorage** [comment]
all ok after update node to 8+
