### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by HowBoutSomeSnus** [okonek/tidal-cli-client#23]
I get this when I try to run tidal-cli:

/usr/lib/node_modules/tidal-cli-client/app/index.js:9
const checkDependencies = async () => {
                                ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

**Comment by nklb** [comment]
I just ran into the same error but then found out what the problem was: 
the async function is not supported by nodejs prior to version 7.6.

So I could make it work by installing a newer version of nodejs. Maybe this works for you as well.

You can find out your installed version by
`node -v`
