### ISSUE TITLE
Can't start client

### ISSUE THREAD

**Issue by shpotes** [okonek/tidal-cli-client#29]
When i run `$ tidal-cli` i get the following error
```
$ tidal-cli 
/usr/local/lib/node_modules/tidal-cli-client/app/index.js:25
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)```

**Comment by HowBoutSomeSnus** [comment]
You have the same problem I had. You need to update node.

**Comment by okonek** [comment]
Yes, that's true.
