### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by jocap** [okonek/tidal-cli-client#62]
Hi,

I'm trying to install tidal-cli-client on OpenBSD. `npm install` works, but when I try to launch `tidal-cli`, nothing happens. It just hangs without any output.

`npm run test` yields the following:

```
  ApiWrapper
    login()
      1) login() should user data object if valid creditnails are passed
      ✓ login() should return an error if invalid creditnals are passed
    apiGetMethods
      2) "before each" hook for "search() should return a list of max 10 with correct type objects if called with a proper query and type and limit 10"

  TempManager
    writeFile()
      ✓ writeFile() should write a file to a temp directory with passed name and return the written file src if existing file is passed
      ✓ writeFile() should write a file to a temp directory with passed name and return the written file src if existing file from url is passed (994ms)
    getFilePath()
      ✓ getFilePath() should return a file path in temp dir with the name and extension passed


  4 passing (1s)
  2 failing

  1) ApiWrapper
       login()
         login() should user data object if valid creditnails are passed:
     Error: Username and password are required arguments of login()
      at Tidal._callee$ (node_modules/tidal-api-wrapper-okonek/lib/index.js:94:23)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /home/john/dev/tmp/tidal-cli-client/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (<anonymous>)
      at new F (node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:36:28)
      at Tidal.<anonymous> (node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
      at Tidal.login (node_modules/tidal-api-wrapper-okonek/lib/index.js:128:21)
      at module.exports.login (app/backend/api/ApiWrapper.js:19:25)
      at Context.it (tests/backend/ApiWrapper.js:28:36)

  2) ApiWrapper
       apiGetMethods
         "before each" hook for "search() should return a list of max 10 with correct type objects if called with a proper query and type and limit 10":
     Error: Username and password are required arguments of login()
      at Tidal._callee$ (node_modules/tidal-api-wrapper-okonek/lib/index.js:94:23)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /home/john/dev/tmp/tidal-cli-client/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (<anonymous>)
      at new F (node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:36:28)
      at Tidal.<anonymous> (node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
      at Tidal.login (node_modules/tidal-api-wrapper-okonek/lib/index.js:128:21)
      at module.exports.login (app/backend/api/ApiWrapper.js:19:25)
      at Context.beforeEach (tests/backend/ApiWrapper.js:49:23)



npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! tidal-cli-client@2.0.6 test: `mocha tests --recursive --timeout 5000`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the tidal-cli-client@2.0.6 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/john/.npm/_logs/2018-12-19T22_11_55_574Z-debug.log
```

Hopefully it's nothing major?

Best regards,
John

**Comment by okonek** [comment]
Have you installed mpv and w3m first?

**Comment by jocap** [comment]
@okonek, yes, I have.

**Comment by okonek** [comment]
Ok, this is strange. Don't you get any error when trying to run the app? Just it doesn't turn on?

**Comment by jocap** [comment]
It just hangs, without any output...

**Comment by okonek** [comment]
I really don't know what to do in here. Maybe when I'll have more time, I could install OpenBSD on vm or docker and check the problem.
