### ISSUE TITLE
Tidal-cli crashed upon starting

### ISSUE THREAD

**Issue by brodel77** [okonek/tidal-cli-client#71]
andrew@andrew-MacPro:~$ tidal-cli
Successfully sent fatal error with eventId 57d19593cf0c435baae4945c9f79392d to the developer
Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel
    at handler (/usr/local/lib/node_modules/tidal-cli-client/node_modules/clipboardy/lib/linux.js:7:9)
    at Object.copySync (/usr/local/lib/node_modules/tidal-cli-client/node_modules/clipboardy/lib/linux.js:33:5)
    at Object.exports.writeSync.input [as writeSync] (/usr/local/lib/node_modules/tidal-cli-client/node_modules/clipboardy/index.js:38:13)
    at paypalLinkCopyButton.bindOnClick (/usr/local/lib/node_modules/tidal-cli-client/app/UI/panels/HomePanel.js:42:15)
    at pressSubscribers.map.x (/usr/local/lib/node_modules/tidal-cli-client/app/UI/uiComponents/basicUI/Button.js:32:6)
    at Array.map (<anonymous>)
    at module.exports.buttonPressed (/usr/local/lib/node_modules/tidal-cli-client/app/UI/uiComponents/basicUI/Button.js:27:26)
    at Button.EventEmitter._emit (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/events.js:94:20)
    at Button.EventEmitter.emit (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/events.js:117:12)
    at Button.press (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/widgets/button.js:53:21)
    at Button.<anonymous> (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/widgets/button.js:35:19)
    at Button.EventEmitter._emit (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/events.js:94:20)
    at Button.EventEmitter.emit (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/events.js:117:12)
    at Program.<anonymous> (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/widgets/screen.js:602:15)
    at emitTwo (events.js:126:13)
    at Program.emit (events.js:214:7)
    at /usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/program.js:410:15
    at Array.forEach (<anonymous>)
    at ReadStream.input.on.input._keypressHandler (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/program.js:408:23)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at /usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/keys.js:318:14
    at Array.forEach (<anonymous>)
    at emitKeys (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/keys.js:134:10)
    at ReadStream.onData (/usr/local/lib/node_modules/tidal-cli-client/node_modules/blessed/lib/keys.js:49:14)
    at emitOne (events.js:121:20)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at TTY.onread (net.js:607:20)
Paste this eventId in the Github issue, so I can help you faster

**Comment by okonek** [comment]
I think you just need to install the required lib. The command to do it is passed in the error.
