### ISSUE TITLE
Cannot start the app

### ISSUE THREAD

**Issue by lucaam** [okonek/tidal-cli-client#8]
Hello dear,

I'm not able to start the app. Used npm to install it.

I've got node and mpv.

This is the error that I receive.

PS: I'm on Ubuntu Boogie based on Ubuntu 17.10. Node version v6.11.4, npm version 3.5.2

```
/usr/local/lib/node_modules/tidal-cli-client/app/Track.js:8
    async updateStreamURL(tidalApi) {
          ^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tidal-cli-client/app/TidalApi.js:2:15)

```

**Comment by iskyd** [comment]
Same here on ubuntu 16.04
node version: 6.12.3
npm version: 3.10.10

**Comment by seljudas** [comment]
Same here, using Ubuntu 16.04, node 6.12.3 and npm 5.6.0.

**Comment by okonek** [comment]
You should update your Node, cause 6.xxx does not support async/await.

**Comment by okonek** [comment]
Can I mark it as closed?

**Comment by jtellnes** [comment]
I had the same problem until I discovered that, on my machine, node was version 6 while nodejs was version 9.5 ...
Removing both node and nodejs and then reinstalling nodejs solved it.
https://stackoverflow.com/questions/18130164/nodejs-vs-node-on-ubuntu-12-04
(Before this I was, for some reason, also able to run tidal-cli with sudo)
